# Generated by Django 3.0.2 on 2020-03-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200301_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.FileField(default='abc.jpeg', upload_to='profilepic'),
        ),
    ]
