# Generated by Django 3.0.2 on 2020-03-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200302_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='abc.jpeg', upload_to='profilepic', verbose_name='image'),
        ),
    ]
