# Generated by Django 3.0.2 on 2020-03-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200302_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='abc.jpeg', upload_to='profilepic'),
        ),
    ]
